# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x0corchestrator\"$\n\x0fRegisterRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"_\n\x10RegisterResponse\x12\x15\n\rassigned_rank\x18\x01 \x01(\x05\x12\x12\n\nworld_size\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x9e\x01\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x19\n\x11\x63urrent_iteration\x18\x03 \x01(\x05\x12\x14\n\x0c\x63urrent_loss\x18\x04 \x01(\x02\x12\x13\n\x0bis_training\x18\x05 \x01(\x08\x12\x1e\n\x16\x63heckpointed_iteration\x18\x06 \x01(\x05\"D\n\x11HeartbeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x19\n\x11should_checkpoint\x18\x02 \x01(\x08\",\n\x17\x43\x61nStartTrainingRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"=\n\x18\x43\x61nStartTrainingResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x12\n\nworld_size\x18\x02 \x01(\x05\"$\n\x0fRecoveryRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"J\n\x10RecoveryResponse\x12\x18\n\x10in_recovery_mode\x18\x01 \x01(\x08\x12\x1c\n\x14\x63heckpoint_iteration\x18\x02 \x01(\x05\x32\xe0\x02\n\x0cOrchestrator\x12I\n\x08Register\x12\x1d.orchestrator.RegisterRequest\x1a\x1e.orchestrator.RegisterResponse\x12P\n\rSendHeartbeat\x12\x1e.orchestrator.HeartbeatRequest\x1a\x1f.orchestrator.HeartbeatResponse\x12\x61\n\x10\x43\x61nStartTraining\x12%.orchestrator.CanStartTrainingRequest\x1a&.orchestrator.CanStartTrainingResponse\x12P\n\x0fGetRecoveryInfo\x12\x1d.orchestrator.RecoveryRequest\x1a\x1e.orchestrator.RecoveryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=36
  _globals['_REGISTERREQUEST']._serialized_end=72
  _globals['_REGISTERRESPONSE']._serialized_start=74
  _globals['_REGISTERRESPONSE']._serialized_end=169
  _globals['_HEARTBEATREQUEST']._serialized_start=172
  _globals['_HEARTBEATREQUEST']._serialized_end=330
  _globals['_HEARTBEATRESPONSE']._serialized_start=332
  _globals['_HEARTBEATRESPONSE']._serialized_end=400
  _globals['_CANSTARTTRAININGREQUEST']._serialized_start=402
  _globals['_CANSTARTTRAININGREQUEST']._serialized_end=446
  _globals['_CANSTARTTRAININGRESPONSE']._serialized_start=448
  _globals['_CANSTARTTRAININGRESPONSE']._serialized_end=509
  _globals['_RECOVERYREQUEST']._serialized_start=511
  _globals['_RECOVERYREQUEST']._serialized_end=547
  _globals['_RECOVERYRESPONSE']._serialized_start=549
  _globals['_RECOVERYRESPONSE']._serialized_end=623
  _globals['_ORCHESTRATOR']._serialized_start=626
  _globals['_ORCHESTRATOR']._serialized_end=978
# @@protoc_insertion_point(module_scope)
